data=load('R-1-1.mat');
R1=data.R;
data=load('R-1-2.mat');
R2=data.R;
data=load('R-1-3.mat');
R3=data.R;
data=load('R-2-1.mat');
R4=data.R;
data=load('R-2-2.mat');
R5=data.R;
data=load('R3.mat');
R6=data.R;
data=load('R-4-1.mat');
R7=data.R;
data=load('R-4-2.mat');
R8=data.R;
R=[R1;R2;R3;R4;R5;R6;R7;R8];
save('R.mat', 'R');

%%%% Time matrix
data=load('T-1-1.mat');
T1=data.T;
data=load('T-1-2.mat');
T2=data.T;
data=load('T-1-3.mat');
T3=data.T;
data=load('T-2-1.mat');
T4=data.T;
data=load('T-2-2.mat');
T5=data.T;
data=load('T3.mat');
T6=data.T;
data=load('T-4-1.mat');
T7=data.T;
data=load('T-4-2.mat');
T8=data.T;
T=[T1;T2;T3;T4;T5;T6;T7;T8];
save('T.mat', 'T');